fpm:
  build: php/
  ports:
   - "9000:9000"
  volumes:
   - ./mysite:/var/www/html/mysite
web:
  image: nginx
  ports:
   - "80:80"
  volumes:
   - ./default:/etc/nginx/sites-enabled/default
   - ./default:/etc/nginx/conf.d/default.conf
  links:
   - fpm 
